version: '2'
services:
  kanboard:
    image: kanboard/kanboard:latest
    ports:
     - "80:80"
    volumes:
     - .:/var/www/app/
     - ./plugins/:/var/www/app/plugins
     - ./data/:/var/www/app/data
     - ./docker/etc/nginx:/etc/nginx
